// Generated by web/scripts/gen-client.mjs from api/openapi.yaml — DO NOT EDIT BY HAND.
// Regenerate with: cd web && bun scripts/gen-client.mjs (then commit the output;
// CI does not regenerate). Types mirror the spec's schemas; every wrapper goes
// through apiClient, so generated calls share the hand-written client's base
// URL ("/api"), bearer-token header, and ApiError error handling.

import { apiClient } from './client';

export interface Cluster {
  name: string;
  api_url: string;
  ingest_url: string;
  sidecar_image: string;
  namespace: string;
  secret_ref: string;
  origin: "operator" | "byoc";
  created_by?: string;
  created_time: string;
  engines_used?: number;
  engines_ceiling?: number;
}

export interface MetricBatch {
  execution_id: number;
  scenario_id?: number;
  run_id?: number;
  shard_index?: number;
  final?: boolean;
  intervals: MetricInterval[];
}

export interface MetricInterval {
  ts?: number;
  label?: string;
  concurrency?: number;
  samples?: number;
  succeeded?: number;
  failed?: number;
  bytes?: number;
  latency?: Record<string, number>;
  response_codes?: Record<string, number>;
  errors?: { message?: string; response_code?: string; count?: number }[];
}

export interface Error {
  message?: string;
}

export interface Diagnostic {
  severity?: "error" | "warning" | "info";
  message?: string;
  line?: number;
  col?: number;
  path?: string;
}

export interface DiagnosticsError {
  message?: string;
  diagnostics?: Diagnostic[];
}

export interface Project {
  id?: number;
  name?: string;
  owner?: string;
  sid?: string;
  tenant_id?: number | null;
  created_time?: string;
}

export interface ProjectSummary {
  project_id: number;
  total_executions: number;
  last_execution_time?: string;
  scenario_count: number;
  template_count: number;
  regressed_count: number;
  last_run: { run_id?: number; outcome?: "passed" | "failed" | "aborted" | "error"; started_at?: string } | null;
  throughput_series: SummaryThroughputPoint[];
}

export interface SummaryThroughputPoint {
  run_id?: number;
  started_at?: string;
  achieved_throughput?: number;
  requested_throughput?: number;
  regressed?: boolean;
}

export interface Scenario {
  id?: number;
  name?: string;
  project_id?: number;
  kind?: "portable" | "native";
  created_time?: string;
  is_template?: boolean;
  template_name?: string;
}

export interface InstantiateRequest {
  name: string;
  project_id: number;
  overrides?: { target_url?: string };
}

export interface Webhook {
  id?: number;
  url?: string;
  has_secret?: boolean;
  enabled?: boolean;
  created_by?: string;
  created_time?: string;
}

export interface RunCompletedEvent {
  event: "run.completed";
  run_id: number;
  execution_id: number;
  project_id: number;
  engine?: string;
  outcome: "passed" | "failed" | "aborted" | "error";
  achieved: { samples?: number; throughput?: number };
  error_rate: number;
  thresholds: { criteria?: string[]; failing?: string[] };
  started_time: string;
  ended_time: string;
  report_url: string;
}

export interface DigestEvent {
  event: "report.digest";
  project_id: number;
  period: "daily" | "weekly";
  window_start: string;
  window_end: string;
  runs_total: number;
  by_outcome: { passed?: number; failed?: number; aborted?: number };
  threshold_failures: number;
  executions?: { execution_id?: number; name?: string; runs?: number; worst_outcome?: string }[];
}

export interface DigestConfig {
  project_id?: number;
  period?: "daily" | "weekly";
  enabled?: boolean;
  last_fired?: string;
}

export interface Digest {
  id?: number;
  period?: string;
  window_start?: string;
  window_end?: string;
  runs_total?: number;
  by_outcome?: { passed?: number; failed?: number; aborted?: number };
  threshold_failures?: number;
  delivery_status?: "pending" | "delivered" | "failed";
  delivered_at?: string;
  executions?: { execution_id?: number; name?: string; runs?: number; worst_outcome?: string }[];
}

export interface LoadProfileEntry {
  name?: string;
  scenario_id?: number;
  concurrency?: number;
  rampup?: number;
  engines?: number;
  duration?: number;
  csv_split?: boolean;
}

export interface ExecutionSummary {
  id?: number;
  name?: string;
  project_id?: number;
  engine?: string;
  kind?: "load" | "calibrate_engine";
  cluster?: string;
  created_time?: string;
}

export interface Execution {
  id?: number;
  name?: string;
  project_id?: number;
  engine?: string;
  kind?: "load" | "calibrate_engine";
  cluster?: string;
  csv_split?: boolean;
  created_time?: string;
  load_profile?: LoadProfileEntry[];
  data?: { filename?: string; url?: string }[];
  calibration?: { criterion?: string; seed_qps?: number; max_qps?: number; max_steps?: number; hold_seconds?: number; cpu?: string; memory?: string };
}

export interface ScenarioReadiness {
  scenario_id?: number;
  engines?: number;
  engines_deployed?: number;
  engines_reachable?: boolean;
}

export interface ExecutionStatus {
  phase?: "idle" | "deployed" | "running";
  status?: ScenarioReadiness[];
  pool_size?: number;
}

export interface EngineDetail {
  name?: string;
  status?: string;
  created_time?: string;
}

export interface Tenant {
  id?: number;
  name?: string;
  display_name?: string;
  status?: string;
  created_time?: string;
}

export interface RoleGrant {
  subject?: string;
  email?: string;
  role?: string;
  granted_by?: string;
  granted_time?: string;
}

export interface Reservation {
  id?: number;
  tenant_id?: number;
  cluster?: string;
  engine_count?: number;
  start?: string;
  end?: string;
  execution_id?: number;
}

export interface Occurrence {
  id?: number;
  fire_time?: string;
  status?: "reserved" | "rejected" | "fired" | "completed";
  reservation_id?: number;
}

export interface Schedule {
  id?: number;
  execution_id?: number;
  tenant_id?: number;
  cluster?: string;
  kind?: "one_shot" | "recurring";
  fire_at?: string;
  recurrence?: string;
  active?: boolean;
  occurrences?: Occurrence[];
}

export interface CampaignServiceBinding {
  project_id?: number;
  execution_id?: number;
}

export interface Campaign {
  id?: number;
  name?: string;
  tenant_id?: number;
  window_start?: string;
  window_end?: string;
  services?: CampaignServiceBinding[];
  active?: boolean;
  aborted_at?: string;
}

export interface FailingCriterion {
  criterion: string;
  unparsed?: boolean;
}

export interface ServiceVerdict {
  project_id?: number;
  execution_id?: number;
  has_report?: boolean;
  outcome?: "passed" | "failed" | "aborted" | "error";
  failing_criteria?: FailingCriterion[];
  short_of_target_qps?: boolean;
  requested_throughput?: number;
  achieved_throughput?: number;
}

export interface OtherLoad {
  execution_id?: number;
  start?: string;
  end?: string;
  engine_count?: number;
}

export interface CampaignVerdict {
  campaign_id?: number;
  services?: ServiceVerdict[];
  go?: boolean;
  other_load?: OtherLoad[];
}

export interface ServiceComparison {
  project_id?: number;
  status?: "improved" | "regressed" | "newly_at_risk" | "still_at_risk" | "steady" | "new" | "dropped";
  has_current?: boolean;
  go?: boolean;
  has_baseline?: boolean;
  baseline_go?: boolean;
}

export interface CampaignComparison {
  campaign_id?: number;
  has_baseline?: boolean;
  baseline_campaign_id?: number;
  services?: ServiceComparison[];
}

export interface CalibrationExecution {
  execution_id?: number;
  name?: string;
  project_id?: number;
  engine?: string;
  cpu?: string;
  memory?: string;
  criterion?: string;
  seed_qps?: number;
  max_qps?: number;
  max_steps?: number;
  hold_seconds?: number;
}

export interface CalibrationStep {
  requested_qps?: number;
  achieved_qps?: number;
  classification?: "engine_saturated" | "target_saturated" | "clean";
}

export interface CalibrationResult {
  saturated_by?: "engine" | "target" | "neither";
  per_pod_qps?: number;
}

export interface CalibrationJob {
  id?: number;
  execution_id?: number;
  phase?: "pending" | "bracketing" | "bisecting" | "done" | "failed";
  step_count?: number;
  next_requested_qps?: number;
  result?: CalibrationResult;
  failure_reason?: string;
  created_time?: string;
  steps?: CalibrationStep[];
}

export interface CapacityProfile {
  scenario_id?: number;
  engine?: string;
  cpu?: string;
  memory?: string;
  per_pod_qps?: number;
  saturated_by?: "engine" | "target" | "neither";
  scenario_fingerprint?: string;
  calibrated_at?: string;
  job_id?: number;
}

export interface CapacityProfileSummary {
  scenario_id?: number;
  engine?: string;
  cpu?: string;
  memory?: string;
  per_pod_qps?: number;
  saturated_by?: "engine" | "target" | "neither";
  calibrated_at?: string;
}

export interface FanOutResult {
  status?: "ok" | "target_limited" | "inconclusive" | "stale" | "no_profile";
  engines?: number;
}

export interface Report {
  execution_id: number;
  scenario_id: number;
  run_id: number;
  engine?: string;
  cluster?: string;
  correlation_id?: string;
  started_at: string;
  ended_at: string;
  outcome: "passed" | "failed" | "aborted" | "error";
  requested: Load;
  achieved: Load;
  error_rate: number;
  latency: Record<string, number>;
  attribution: Attribution;
  errors?: ErrorSignature[];
  labels?: LabelSummary[];
  project_id?: number;
  baggage?: string;
  criteria?: string[] | null;
  failing_criteria?: FailingCriterion[] | null;
}

export interface Series {
  points?: SeriesPoint[];
}

export interface SeriesPoint {
  ts?: number;
  vus?: number;
  rps?: number;
  err_pct?: number;
  latency?: Record<string, number>;
}

export interface Trend {
  execution_id?: number;
  points?: TrendPoint[];
}

export interface TrendPoint {
  run_id?: number;
  outcome?: "passed" | "failed" | "aborted" | "error";
  achieved_throughput?: number;
  requested_throughput?: number;
  error_rate?: number;
  p50?: number;
  p90?: number;
  p95?: number;
  p99?: number;
  hit_target_qps?: boolean;
  has_comparable_predecessor?: boolean;
  regressed?: boolean;
}

export interface SignatureHistoryRow {
  label?: string;
  response_code?: string;
  side?: "target" | "engine" | "unknown";
  total_count?: number;
  run_count?: number;
}

export interface SignatureBreakdown {
  key?: string;
  total_count?: number;
  rows?: SignatureHistoryRow[];
}

export interface ErrorSignatureHistory {
  execution_id?: number;
  grouped_by?: "label" | "response_code";
  groups?: SignatureBreakdown[];
}

export interface Load {
  concurrency: number;
  throughput: number;
  duration_seconds?: number;
  samples?: number;
  failed?: number;
}

export interface Attribution {
  target: number;
  engine: number;
  unknown: number;
}

export interface ErrorSignature {
  label: string;
  response_code?: string;
  side: "target" | "engine" | "unknown";
  count: number;
  exemplars?: string[];
}

export interface LabelSummary {
  label: string;
  samples: number;
  failed: number;
  error_rate: number;
  latency: Record<string, number>;
  statuses?: StatusLabel[];
}

export interface StatusLabel {
  code: string;
  count: number;
}

// Typed path constants: one builder per operation, params interpolated.
export const paths = {
  getHealthz: () => `/healthz`,
  getMetrics: () => `/metrics`,
  getSessionProfiles: () => `/session/profiles`,
  getApmLinks: () => `/apm-links`,
  postSession: () => `/session`,
  deleteSession: () => `/session`,
  getMe: () => `/me`,
  getProjects: () => `/projects`,
  postProjects: () => `/projects`,
  getProjectsByProjectId: (projectId: number | string) => `/projects/${projectId}`,
  deleteProjectsByProjectId: (projectId: number | string) => `/projects/${projectId}`,
  getProjectsByProjectIdSummary: (projectId: number | string) => `/projects/${projectId}/summary`,
  getProjectsByProjectIdWebhooks: (projectId: number | string) => `/projects/${projectId}/webhooks`,
  postProjectsByProjectIdWebhooks: (projectId: number | string) => `/projects/${projectId}/webhooks`,
  deleteProjectsByProjectIdWebhooksByWebhookId: (projectId: number | string, webhookId: number | string) => `/projects/${projectId}/webhooks/${webhookId}`,
  putProjectsByProjectIdWebhooksByWebhookIdEnabled: (projectId: number | string, webhookId: number | string) => `/projects/${projectId}/webhooks/${webhookId}/enabled`,
  getProjectsByProjectIdDigest: (projectId: number | string) => `/projects/${projectId}/digest`,
  putProjectsByProjectIdDigest: (projectId: number | string) => `/projects/${projectId}/digest`,
  deleteProjectsByProjectIdDigest: (projectId: number | string) => `/projects/${projectId}/digest`,
  getProjectsByProjectIdDigests: (projectId: number | string) => `/projects/${projectId}/digests`,
  getTemplates: () => `/templates`,
  getScenarios: () => `/scenarios`,
  postScenarios: () => `/scenarios`,
  postScenariosImport: () => `/scenarios/import`,
  postScenariosByScenarioIdInstantiate: (scenarioId: number | string) => `/scenarios/${scenarioId}/instantiate`,
  getScenariosByScenarioIdExecutions: (scenarioId: number | string) => `/scenarios/${scenarioId}/executions`,
  getScenariosByScenarioId: (scenarioId: number | string) => `/scenarios/${scenarioId}`,
  deleteScenariosByScenarioId: (scenarioId: number | string) => `/scenarios/${scenarioId}`,
  getScenariosByScenarioIdFiles: (scenarioId: number | string) => `/scenarios/${scenarioId}/files`,
  putScenariosByScenarioIdFiles: (scenarioId: number | string) => `/scenarios/${scenarioId}/files`,
  deleteScenariosByScenarioIdFiles: (scenarioId: number | string) => `/scenarios/${scenarioId}/files`,
  getScenariosByScenarioIdRequests: (scenarioId: number | string) => `/scenarios/${scenarioId}/requests`,
  putScenariosByScenarioIdRequests: (scenarioId: number | string) => `/scenarios/${scenarioId}/requests`,
  postScenariosByScenarioIdRequestsValidate: (scenarioId: number | string) => `/scenarios/${scenarioId}/requests/validate`,
  getExecutions: () => `/executions`,
  postExecutions: () => `/executions`,
  getExecutionsByExecutionId: (executionId: number | string) => `/executions/${executionId}`,
  deleteExecutionsByExecutionId: (executionId: number | string) => `/executions/${executionId}`,
  getExecutionsByExecutionIdFiles: (executionId: number | string) => `/executions/${executionId}/files`,
  putExecutionsByExecutionIdFiles: (executionId: number | string) => `/executions/${executionId}/files`,
  deleteExecutionsByExecutionIdFiles: (executionId: number | string) => `/executions/${executionId}/files`,
  getExecutionsByExecutionIdConfig: (executionId: number | string) => `/executions/${executionId}/config`,
  putExecutionsByExecutionIdConfig: (executionId: number | string) => `/executions/${executionId}/config`,
  postExecutionsByExecutionIdDeploy: (executionId: number | string) => `/executions/${executionId}/deploy`,
  postExecutionsByExecutionIdTrigger: (executionId: number | string) => `/executions/${executionId}/trigger`,
  postExecutionsByExecutionIdStop: (executionId: number | string) => `/executions/${executionId}/stop`,
  postExecutionsByExecutionIdPurge: (executionId: number | string) => `/executions/${executionId}/purge`,
  getExecutionsByExecutionIdStatus: (executionId: number | string) => `/executions/${executionId}/status`,
  getExecutionsByExecutionIdEngines: (executionId: number | string) => `/executions/${executionId}/engines`,
  getExecutionsByExecutionIdScenariosByScenarioIdLogs: (executionId: number | string, scenarioId: number | string) => `/executions/${executionId}/scenarios/${scenarioId}/logs`,
  getExecutionsByExecutionIdStream: (executionId: number | string) => `/executions/${executionId}/stream`,
  getExecutionsByExecutionIdSchedules: (executionId: number | string) => `/executions/${executionId}/schedules`,
  postExecutionsByExecutionIdSchedules: (executionId: number | string) => `/executions/${executionId}/schedules`,
  deleteExecutionsByExecutionIdSchedulesByScheduleId: (executionId: number | string, scheduleId: number | string) => `/executions/${executionId}/schedules/${scheduleId}`,
  getTenantsByTenantIdCampaigns: (tenantId: number | string) => `/tenants/${tenantId}/campaigns`,
  postTenantsByTenantIdCampaigns: (tenantId: number | string) => `/tenants/${tenantId}/campaigns`,
  getCampaigns: () => `/campaigns`,
  getCampaignsByCampaignId: (campaignId: number | string) => `/campaigns/${campaignId}`,
  putCampaignsByCampaignId: (campaignId: number | string) => `/campaigns/${campaignId}`,
  postCampaignsByCampaignIdAbort: (campaignId: number | string) => `/campaigns/${campaignId}/abort`,
  getCampaignsByCampaignIdVerdict: (campaignId: number | string) => `/campaigns/${campaignId}/verdict`,
  getCampaignsByCampaignIdComparison: (campaignId: number | string) => `/campaigns/${campaignId}/comparison`,
  postCalibrations: () => `/calibrations`,
  postExecutionsByExecutionIdCalibrationTrigger: (executionId: number | string) => `/executions/${executionId}/calibration/trigger`,
  getCalibrationsByJobId: (jobId: number | string) => `/calibrations/${jobId}`,
  getScenariosByScenarioIdCapacityProfile: (scenarioId: number | string) => `/scenarios/${scenarioId}/capacity-profile`,
  getCapacityProfiles: () => `/capacity-profiles`,
  getScenariosByScenarioIdCapacityProfileFanout: (scenarioId: number | string) => `/scenarios/${scenarioId}/capacity-profile/fanout`,
  getExecutionsByExecutionIdReports: (executionId: number | string) => `/executions/${executionId}/reports`,
  getExecutionsByExecutionIdTrend: (executionId: number | string) => `/executions/${executionId}/trend`,
  getExecutionsByExecutionIdErrorSignatures: (executionId: number | string) => `/executions/${executionId}/error-signatures`,
  getRunsCompare: () => `/runs/compare`,
  getRunsByRunIdReport: (runId: number | string) => `/runs/${runId}/report`,
  getRunsByRunIdSeries: (runId: number | string) => `/runs/${runId}/series`,
  getRunsByRunIdExport: (runId: number | string) => `/runs/${runId}/export`,
  getRunsByRunIdScenariosByScenarioIdShardsByShardLog: (runId: number | string, scenarioId: number | string, shard: number | string) => `/runs/${runId}/scenarios/${scenarioId}/shards/${shard}/log`,
  getRunsByRunIdScenariosByScenarioIdShardsByShardConfig: (runId: number | string, scenarioId: number | string, shard: number | string) => `/runs/${runId}/scenarios/${scenarioId}/shards/${shard}/config`,
  getRunsByRunIdShare: (runId: number | string) => `/runs/${runId}/share`,
  postRunsByRunIdShare: (runId: number | string) => `/runs/${runId}/share`,
  deleteRunsByRunIdShareByToken: (runId: number | string, token: number | string) => `/runs/${runId}/share/${token}`,
  getShareByToken: (token: number | string) => `/share/${token}`,
  getUsageHistory: () => `/usage/history`,
  getUsageSummary: () => `/usage/summary`,
  getAdminExecutions: () => `/admin/executions`,
  getAdminNodes: () => `/admin/nodes`,
  postAdminAbort: () => `/admin/abort`,
  getTenants: () => `/tenants`,
  postTenants: () => `/tenants`,
  getTenantsByTenantId: (tenantId: number | string) => `/tenants/${tenantId}`,
  patchTenantsByTenantId: (tenantId: number | string) => `/tenants/${tenantId}`,
  getTenantsByTenantIdQuota: (tenantId: number | string) => `/tenants/${tenantId}/quota`,
  putTenantsByTenantIdQuota: (tenantId: number | string) => `/tenants/${tenantId}/quota`,
  getTenantsByTenantIdReservations: (tenantId: number | string) => `/tenants/${tenantId}/reservations`,
  getTenantsByTenantIdRoles: (tenantId: number | string) => `/tenants/${tenantId}/roles`,
  postTenantsByTenantIdRoles: (tenantId: number | string) => `/tenants/${tenantId}/roles`,
  deleteTenantsByTenantIdRoles: (tenantId: number | string) => `/tenants/${tenantId}/roles`,
  postRoles: () => `/roles`,
  deleteRoles: () => `/roles`,
  getClusters: () => `/clusters`,
  postClusters: () => `/clusters`,
  postClustersByNameRotateIngestToken: (name: number | string) => `/clusters/${name}/rotate-ingest-token`,
  getClustersByName: (name: number | string) => `/clusters/${name}`,
  putClustersByName: (name: number | string) => `/clusters/${name}`,
  deleteClustersByName: (name: number | string) => `/clusters/${name}`,
  postIngest: () => `/ingest`,
  getFilesByKindByIdByName: (kind: number | string, id: number | string, name: number | string) => `/files/${kind}/${id}/${name}`,
} as const;

/** Liveness probe */
export function getHealthz(): Promise<void> {
  return apiClient.get<void>(paths.getHealthz());
}

/** Prometheus metrics exposition */
export function getMetrics(): Promise<string> {
  return apiClient.text(paths.getMetrics());
}

/** List the demo personas the picker may offer */
export function getSessionProfiles(): Promise<{ profiles?: { id?: string; name?: string }[] }> {
  return apiClient.get<{ profiles?: { id?: string; name?: string }[] }>(paths.getSessionProfiles());
}

/** The deployment's configured APM link-out templates */
export function getApmLinks(): Promise<{ name?: string; url_template?: string }[]> {
  return apiClient.get<{ name?: string; url_template?: string }[]>(paths.getApmLinks());
}

/** Authenticate as a demo persona */
export function postSession(body: { profile: string }): Promise<void> {
  return apiClient.request<void>(paths.postSession(), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
}

/** Log out (expire the session cookie) */
export function deleteSession(): Promise<void> {
  return apiClient.request<void>(paths.deleteSession(), { method: 'DELETE' });
}

/** The authenticated caller's identity and permission map */
export function getMe(): Promise<{ subject?: string; name?: string; email?: string; global_roles?: string[]; tenants?: Record<string, string[]>; permissions?: Record<string, string[]>; demo?: boolean }> {
  return apiClient.get<{ subject?: string; name?: string; email?: string; global_roles?: string[]; tenants?: Record<string, string[]>; permissions?: Record<string, string[]>; demo?: boolean }>(paths.getMe());
}

/** List projects visible to the caller */
export function getProjects(): Promise<Project[]> {
  return apiClient.get<Project[]>(paths.getProjects());
}

/** Create a project */
export function postProjects(body: { name: string; owner: string; sid?: string; tenant_id?: number }): Promise<Project> {
  return apiClient.post<Project>(paths.postProjects(), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Get a project */
export function getProjectsByProjectId(projectId: number | string): Promise<Project> {
  return apiClient.get<Project>(paths.getProjectsByProjectId(projectId));
}

/** Delete a project */
export function deleteProjectsByProjectId(projectId: number | string): Promise<void> {
  return apiClient.request<void>(paths.deleteProjectsByProjectId(projectId), { method: 'DELETE' });
}

/** One project's dashboard summary */
export function getProjectsByProjectIdSummary(projectId: number | string, opts?: { query?: { limit?: number | string } }): Promise<ProjectSummary> {
  return apiClient.get<ProjectSummary>(paths.getProjectsByProjectIdSummary(projectId) + toQuery(opts?.query ?? {}));
}

/** List a project's webhooks */
export function getProjectsByProjectIdWebhooks(projectId: number | string): Promise<Webhook[]> {
  return apiClient.get<Webhook[]>(paths.getProjectsByProjectIdWebhooks(projectId));
}

/** Register a run-completion webhook for a project */
export function postProjectsByProjectIdWebhooks(projectId: number | string, body: { url: string; secret?: string }): Promise<Webhook> {
  return apiClient.post<Webhook>(paths.postProjectsByProjectIdWebhooks(projectId), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Delete one of a project's webhooks */
export function deleteProjectsByProjectIdWebhooksByWebhookId(projectId: number | string, webhookId: number | string): Promise<void> {
  return apiClient.request<void>(paths.deleteProjectsByProjectIdWebhooksByWebhookId(projectId, webhookId), { method: 'DELETE' });
}

/** Pause or resume one of a project's webhooks */
export function putProjectsByProjectIdWebhooksByWebhookIdEnabled(projectId: number | string, webhookId: number | string, body: { enabled: boolean }): Promise<{ message?: string }> {
  return apiClient.post<{ message?: string }>(paths.putProjectsByProjectIdWebhooksByWebhookIdEnabled(projectId, webhookId), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Read a project's digest configuration */
export function getProjectsByProjectIdDigest(projectId: number | string): Promise<DigestConfig> {
  return apiClient.get<DigestConfig>(paths.getProjectsByProjectIdDigest(projectId));
}

/** Configure (and enable) a project's periodic digest */
export function putProjectsByProjectIdDigest(projectId: number | string, body: { period: "daily" | "weekly" }): Promise<DigestConfig> {
  return apiClient.post<DigestConfig>(paths.putProjectsByProjectIdDigest(projectId), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Turn a project's digest off */
export function deleteProjectsByProjectIdDigest(projectId: number | string): Promise<void> {
  return apiClient.request<void>(paths.deleteProjectsByProjectIdDigest(projectId), { method: 'DELETE' });
}

/** List a project's stored digests */
export function getProjectsByProjectIdDigests(projectId: number | string, opts?: { query?: { limit?: number | string } }): Promise<Digest[]> {
  return apiClient.get<Digest[]>(paths.getProjectsByProjectIdDigests(projectId) + toQuery(opts?.query ?? {}));
}

/** List the template catalog */
export function getTemplates(): Promise<Scenario[]> {
  return apiClient.get<Scenario[]>(paths.getTemplates());
}

/** List the caller's scenarios */
export function getScenarios(opts?: { query?: { project_id?: number | string } }): Promise<Scenario[]> {
  return apiClient.get<Scenario[]>(paths.getScenarios() + toQuery(opts?.query ?? {}));
}

/** Create a scenario */
export function postScenarios(body: { name: string; project_id: number }): Promise<Scenario> {
  return apiClient.post<Scenario>(paths.postScenarios(), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Import a JMeter plan as a scenario */
export function postScenariosImport(): Promise<{ scenario?: Scenario; report?: { test_plan_name?: string; thread_groups?: { name?: string; threads?: number; ramp_up_seconds?: number; duration_seconds?: number }[]; data_files?: string[]; findings?: { kind?: "load-overridden" | "unreachable-path" | "listener-ignored" | "external-reporting"; element?: string; detail?: string }[] } }> {
  return apiClient.request<{ scenario?: Scenario; report?: { test_plan_name?: string; thread_groups?: { name?: string; threads?: number; ramp_up_seconds?: number; duration_seconds?: number }[]; data_files?: string[]; findings?: { kind?: "load-overridden" | "unreachable-path" | "listener-ignored" | "external-reporting"; element?: string; detail?: string }[] } }>(paths.postScenariosImport(), { method: 'POST' });
}

/** Instantiate a template into a new scenario */
export function postScenariosByScenarioIdInstantiate(scenarioId: number | string, body: InstantiateRequest): Promise<Scenario> {
  return apiClient.request<Scenario>(paths.postScenariosByScenarioIdInstantiate(scenarioId), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
}

/** List a scenario's executions */
export function getScenariosByScenarioIdExecutions(scenarioId: number | string): Promise<ExecutionSummary[]> {
  return apiClient.get<ExecutionSummary[]>(paths.getScenariosByScenarioIdExecutions(scenarioId));
}

/** Get a scenario and its files */
export function getScenariosByScenarioId(scenarioId: number | string): Promise<Scenario> {
  return apiClient.get<Scenario>(paths.getScenariosByScenarioId(scenarioId));
}

/** Delete a scenario */
export function deleteScenariosByScenarioId(scenarioId: number | string): Promise<void> {
  return apiClient.request<void>(paths.deleteScenariosByScenarioId(scenarioId), { method: 'DELETE' });
}

/** List a scenario's files */
export function getScenariosByScenarioIdFiles(scenarioId: number | string): Promise<{ test_file?: string; data?: string[] }> {
  return apiClient.get<{ test_file?: string; data?: string[] }>(paths.getScenariosByScenarioIdFiles(scenarioId));
}

/** Upload a script or data file */
export function putScenariosByScenarioIdFiles(scenarioId: number | string): Promise<void> {
  return apiClient.request<void>(paths.putScenariosByScenarioIdFiles(scenarioId), { method: 'PUT' });
}

/** Delete one of a scenario's files */
export function deleteScenariosByScenarioIdFiles(scenarioId: number | string, opts?: { query?: { filename?: string } }): Promise<void> {
  return apiClient.request<void>(paths.deleteScenariosByScenarioIdFiles(scenarioId) + toQuery(opts?.query ?? {}), { method: 'DELETE' });
}

/** Get a portable scenario's stored declarative workload */
export function getScenariosByScenarioIdRequests(scenarioId: number | string): Promise<string> {
  return apiClient.text(paths.getScenariosByScenarioIdRequests(scenarioId));
}

/** Upload a portable scenario's declarative workload */
export function putScenariosByScenarioIdRequests(scenarioId: number | string, body: string): Promise<{ message?: string }> {
  return apiClient.request<{ message?: string }>(paths.putScenariosByScenarioIdRequests(scenarioId), {
    method: 'PUT',
    headers: { 'Content-Type': 'text/yaml' },
    body,
  });
}

/** Validate a declarative workload fragment without storing it */
export function postScenariosByScenarioIdRequestsValidate(scenarioId: number | string, body: string): Promise<{ valid?: boolean; diagnostics?: Diagnostic[] }> {
  return apiClient.request<{ valid?: boolean; diagnostics?: Diagnostic[] }>(paths.postScenariosByScenarioIdRequestsValidate(scenarioId), {
    method: 'POST',
    headers: { 'Content-Type': 'text/yaml' },
    body,
  });
}

/** List the caller's executions */
export function getExecutions(): Promise<ExecutionSummary[]> {
  return apiClient.get<ExecutionSummary[]>(paths.getExecutions());
}

/** Create an execution */
export function postExecutions(body: { name: string; project_id: number; engine?: "jmeter" | "k6" | "gatling" | "locust" | "apiritif" | "ab" | "siege" }): Promise<Execution> {
  return apiClient.post<Execution>(paths.postExecutions(), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Get an execution and its load profile */
export function getExecutionsByExecutionId(executionId: number | string): Promise<Execution> {
  return apiClient.get<Execution>(paths.getExecutionsByExecutionId(executionId));
}

/** Delete an execution */
export function deleteExecutionsByExecutionId(executionId: number | string): Promise<void> {
  return apiClient.request<void>(paths.deleteExecutionsByExecutionId(executionId), { method: 'DELETE' });
}

/** List an execution's data files */
export function getExecutionsByExecutionIdFiles(executionId: number | string): Promise<string[]> {
  return apiClient.get<string[]>(paths.getExecutionsByExecutionIdFiles(executionId));
}

/** Upload a data file shared by the execution's scenarios */
export function putExecutionsByExecutionIdFiles(executionId: number | string): Promise<void> {
  return apiClient.request<void>(paths.putExecutionsByExecutionIdFiles(executionId), { method: 'PUT' });
}

/** Delete one of an execution's data files */
export function deleteExecutionsByExecutionIdFiles(executionId: number | string, opts?: { query?: { filename?: string } }): Promise<void> {
  return apiClient.request<void>(paths.deleteExecutionsByExecutionIdFiles(executionId) + toQuery(opts?.query ?? {}), { method: 'DELETE' });
}

/** Get the execution's load profile */
export function getExecutionsByExecutionIdConfig(executionId: number | string): Promise<LoadProfileEntry[]> {
  return apiClient.get<LoadProfileEntry[]>(paths.getExecutionsByExecutionIdConfig(executionId));
}

/** Replace the execution's load profile */
export function putExecutionsByExecutionIdConfig(executionId: number | string, body: { name?: string; project_id?: number; execution_id?: number; csv_split?: boolean; criteria?: string[]; tests?: { scenario_id?: number; name?: string; concurrency?: number; rampup?: number; duration?: number; engines?: number; throughput?: number; csv_split?: boolean }[] }): Promise<void> {
  return apiClient.request<void>(paths.putExecutionsByExecutionIdConfig(executionId), {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
}

/** Deploy the execution's engines */
export function postExecutionsByExecutionIdDeploy(executionId: number | string): Promise<void> {
  return apiClient.request<void>(paths.postExecutionsByExecutionIdDeploy(executionId), { method: 'POST' });
}

/** Start the run */
export function postExecutionsByExecutionIdTrigger(executionId: number | string): Promise<void> {
  return apiClient.request<void>(paths.postExecutionsByExecutionIdTrigger(executionId), { method: 'POST' });
}

/** Stop the run, leaving engines deployed */
export function postExecutionsByExecutionIdStop(executionId: number | string): Promise<void> {
  return apiClient.request<void>(paths.postExecutionsByExecutionIdStop(executionId), { method: 'POST' });
}

/** Tear down all engines */
export function postExecutionsByExecutionIdPurge(executionId: number | string): Promise<void> {
  return apiClient.request<void>(paths.postExecutionsByExecutionIdPurge(executionId), { method: 'POST' });
}

/** Report phase and per-scenario engine readiness */
export function getExecutionsByExecutionIdStatus(executionId: number | string): Promise<ExecutionStatus> {
  return apiClient.get<ExecutionStatus>(paths.getExecutionsByExecutionIdStatus(executionId));
}

/** List the execution's engine pods */
export function getExecutionsByExecutionIdEngines(executionId: number | string): Promise<{ ingress_ip?: string; engines?: EngineDetail[] }> {
  return apiClient.get<{ ingress_ip?: string; engines?: EngineDetail[] }>(paths.getExecutionsByExecutionIdEngines(executionId));
}

/** Fetch the logs of a scenario's first engine pod */
export function getExecutionsByExecutionIdScenariosByScenarioIdLogs(executionId: number | string, scenarioId: number | string): Promise<string> {
  return apiClient.text(paths.getExecutionsByExecutionIdScenariosByScenarioIdLogs(executionId, scenarioId));
}

/** Stream live run metrics as server-sent events */
export function getExecutionsByExecutionIdStream(executionId: number | string): Promise<string> {
  return apiClient.text(paths.getExecutionsByExecutionIdStream(executionId));
}

/** List an execution's schedules and their occurrences' statuses */
export function getExecutionsByExecutionIdSchedules(executionId: number | string): Promise<Schedule[]> {
  return apiClient.get<Schedule[]>(paths.getExecutionsByExecutionIdSchedules(executionId));
}

/** Create a time-triggered schedule for the execution */
export function postExecutionsByExecutionIdSchedules(executionId: number | string, body: { tenant_id: number; cluster?: string; kind: "one_shot" | "recurring"; fire_at?: string; recurrence?: string }): Promise<Schedule> {
  return apiClient.post<Schedule>(paths.postExecutionsByExecutionIdSchedules(executionId), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Delete a schedule */
export function deleteExecutionsByExecutionIdSchedulesByScheduleId(executionId: number | string, scheduleId: number | string): Promise<{ message?: string }> {
  return apiClient.request<{ message?: string }>(paths.deleteExecutionsByExecutionIdSchedulesByScheduleId(executionId, scheduleId), { method: 'DELETE' });
}

/** List a tenant's campaigns */
export function getTenantsByTenantIdCampaigns(tenantId: number | string): Promise<Campaign[]> {
  return apiClient.get<Campaign[]>(paths.getTenantsByTenantIdCampaigns(tenantId));
}

/** Define a campaign -- a window and its participating services */
export function postTenantsByTenantIdCampaigns(tenantId: number | string, body: { name: string; window_start: string; window_end: string; service_project_id: number[]; service_execution_id: number[] }): Promise<Campaign> {
  return apiClient.post<Campaign>(paths.postTenantsByTenantIdCampaigns(tenantId), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** List the caller's campaigns across every tenant they hold a role in */
export function getCampaigns(): Promise<Campaign[]> {
  return apiClient.get<Campaign[]>(paths.getCampaigns());
}

/** Get one campaign */
export function getCampaignsByCampaignId(campaignId: number | string): Promise<Campaign> {
  return apiClient.get<Campaign>(paths.getCampaignsByCampaignId(campaignId));
}

/** Edit a campaign's preparation-time definition */
export function putCampaignsByCampaignId(campaignId: number | string, body: { name: string; window_start: string; window_end: string; service_project_id: number[]; service_execution_id: number[] }): Promise<Campaign> {
  return apiClient.post<Campaign>(paths.putCampaignsByCampaignId(campaignId), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Abort a campaign */
export function postCampaignsByCampaignIdAbort(campaignId: number | string): Promise<Campaign> {
  return apiClient.request<Campaign>(paths.postCampaignsByCampaignIdAbort(campaignId), { method: 'POST' });
}

/** Get a campaign's rolled-up verdict */
export function getCampaignsByCampaignIdVerdict(campaignId: number | string): Promise<CampaignVerdict> {
  return apiClient.get<CampaignVerdict>(paths.getCampaignsByCampaignIdVerdict(campaignId));
}

/** Compare a campaign's per-service go/no-go against a baseline campaign */
export function getCampaignsByCampaignIdComparison(campaignId: number | string, opts?: { query?: { baseline?: number | string } }): Promise<CampaignComparison> {
  return apiClient.get<CampaignComparison>(paths.getCampaignsByCampaignIdComparison(campaignId) + toQuery(opts?.query ?? {}));
}

/** Configure a new CalibrateEngine execution */
export function postCalibrations(body: { project_id: number; name: string; engine: string; criterion: string; cpu: string; memory: string; scenario_id: number; source_execution_id: number; seed_qps?: number; max_qps?: number; max_steps?: number; hold_seconds?: number }): Promise<CalibrationExecution> {
  return apiClient.post<CalibrationExecution>(paths.postCalibrations(), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Start a fresh calibration search */
export function postExecutionsByExecutionIdCalibrationTrigger(executionId: number | string): Promise<CalibrationJob> {
  return apiClient.request<CalibrationJob>(paths.postExecutionsByExecutionIdCalibrationTrigger(executionId), { method: 'POST' });
}

/** Get a calibration job's status and progress */
export function getCalibrationsByJobId(jobId: number | string): Promise<CalibrationJob> {
  return apiClient.get<CalibrationJob>(paths.getCalibrationsByJobId(jobId));
}

/** Get the stored calibration profile for one exact pod size */
export function getScenariosByScenarioIdCapacityProfile(scenarioId: number | string, opts?: { query?: { engine?: string; cpu?: string; memory?: string } }): Promise<CapacityProfile> {
  return apiClient.get<CapacityProfile>(paths.getScenariosByScenarioIdCapacityProfile(scenarioId) + toQuery(opts?.query ?? {}));
}

/** List every stored capacity profile the caller may see */
export function getCapacityProfiles(): Promise<CapacityProfileSummary[]> {
  return apiClient.get<CapacityProfileSummary[]>(paths.getCapacityProfiles());
}

/** Turn a target aggregate QPS into a required engine count */
export function getScenariosByScenarioIdCapacityProfileFanout(scenarioId: number | string, opts?: { query?: { engine?: string; cpu?: string; memory?: string; target_qps?: number | string } }): Promise<FanOutResult> {
  return apiClient.get<FanOutResult>(paths.getScenariosByScenarioIdCapacityProfileFanout(scenarioId) + toQuery(opts?.query ?? {}));
}

/** List an execution's reports, most recent first */
export function getExecutionsByExecutionIdReports(executionId: number | string, opts?: { query?: { limit?: number | string } }): Promise<Report[] | null> {
  return apiClient.get<Report[] | null>(paths.getExecutionsByExecutionIdReports(executionId) + toQuery(opts?.query ?? {}));
}

/** An execution's run-over-run trend */
export function getExecutionsByExecutionIdTrend(executionId: number | string, opts?: { query?: { limit?: number | string } }): Promise<Trend> {
  return apiClient.get<Trend>(paths.getExecutionsByExecutionIdTrend(executionId) + toQuery(opts?.query ?? {}));
}

/** An execution's error signatures aggregated across every run */
export function getExecutionsByExecutionIdErrorSignatures(executionId: number | string, opts?: { query?: { by?: "label" | "code" } }): Promise<ErrorSignatureHistory> {
  return apiClient.get<ErrorSignatureHistory>(paths.getExecutionsByExecutionIdErrorSignatures(executionId) + toQuery(opts?.query ?? {}));
}

/** Fetch several runs' reports in one response, request order preserved */
export function getRunsCompare(opts?: { query?: { "run_ids[]"?: Array<number>; run_a?: number | string; run_b?: number | string } }): Promise<Report[]> {
  return apiClient.get<Report[]>(paths.getRunsCompare() + toQuery(opts?.query ?? {}));
}

/** Fetch a run's stored report */
export function getRunsByRunIdReport(runId: number | string): Promise<Report> {
  return apiClient.get<Report>(paths.getRunsByRunIdReport(runId));
}

/** Fetch a run's per-second series */
export function getRunsByRunIdSeries(runId: number | string): Promise<Series> {
  return apiClient.get<Series>(paths.getRunsByRunIdSeries(runId));
}

/** Export a run's report and series */
export function getRunsByRunIdExport(runId: number | string, opts?: { query?: { format?: "json" | "csv" } }): Promise<{ report?: Report; series?: Series }> {
  return apiClient.get<{ report?: Report; series?: Series }>(paths.getRunsByRunIdExport(runId) + toQuery(opts?.query ?? {}));
}

/** Fetch a shard's captured engine log */
export function getRunsByRunIdScenariosByScenarioIdShardsByShardLog(runId: number | string, scenarioId: number | string, shard: number | string): Promise<string> {
  return apiClient.text(paths.getRunsByRunIdScenariosByScenarioIdShardsByShardLog(runId, scenarioId, shard));
}

/** Fetch a shard's compiled Taurus config, exactly as the run used it */
export function getRunsByRunIdScenariosByScenarioIdShardsByShardConfig(runId: number | string, scenarioId: number | string, shard: number | string): Promise<string> {
  return apiClient.text(paths.getRunsByRunIdScenariosByScenarioIdShardsByShardConfig(runId, scenarioId, shard));
}

/** List a run's share links */
export function getRunsByRunIdShare(runId: number | string): Promise<{ token: string; created_by?: string; created_time: string; expires_at?: string | null }[]> {
  return apiClient.get<{ token: string; created_by?: string; created_time: string; expires_at?: string | null }[]>(paths.getRunsByRunIdShare(runId));
}

/** Issue a share link for a run's report */
export function postRunsByRunIdShare(runId: number | string, body: { expires_in_hours?: number }): Promise<{ token: string; url: string; expires_at?: string | null }> {
  return apiClient.request<{ token: string; url: string; expires_at?: string | null }>(paths.postRunsByRunIdShare(runId), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
}

/** Revoke one share link */
export function deleteRunsByRunIdShareByToken(runId: number | string, token: number | string): Promise<void> {
  return apiClient.request<void>(paths.deleteRunsByRunIdShareByToken(runId, token), { method: 'DELETE' });
}

/** Fetch a run's report through a share link (no authentication) */
export function getShareByToken(token: number | string): Promise<Report> {
  return apiClient.get<Report>(paths.getShareByToken(token));
}

/** Engine usage history */
export function getUsageHistory(opts?: { query?: { from?: string; to?: string } }): Promise<unknown> {
  return apiClient.get<unknown>(paths.getUsageHistory() + toQuery(opts?.query ?? {}));
}

/** Aggregated engine usage */
export function getUsageSummary(opts?: { query?: { from?: string; to?: string } }): Promise<unknown> {
  return apiClient.get<unknown>(paths.getUsageSummary() + toQuery(opts?.query ?? {}));
}

/** List currently deployed executions */
export function getAdminExecutions(): Promise<unknown> {
  return apiClient.get<unknown>(paths.getAdminExecutions());
}

/** Summarise the node pools backing engine capacity */
export function getAdminNodes(): Promise<unknown> {
  return apiClient.get<unknown>(paths.getAdminNodes());
}

/** Kill-switch -- tear down every in-flight execution matching a scope */
export function postAdminAbort(body: { scope: "tenant" | "cluster" | "campaign" | "execution_list"; value: string }): Promise<{ aborted?: number[] }> {
  return apiClient.post<{ aborted?: number[] }>(paths.postAdminAbort(), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** List tenants */
export function getTenants(): Promise<Tenant[]> {
  return apiClient.get<Tenant[]>(paths.getTenants());
}

/** Create a tenant */
export function postTenants(body: { name: string; display_name: string }): Promise<Tenant> {
  return apiClient.post<Tenant>(paths.postTenants(), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Get a tenant */
export function getTenantsByTenantId(tenantId: number | string): Promise<Tenant> {
  return apiClient.get<Tenant>(paths.getTenantsByTenantId(tenantId));
}

/** Set a tenant's status */
export function patchTenantsByTenantId(tenantId: number | string, body: { status: string }): Promise<void> {
  return apiClient.post<void>(paths.patchTenantsByTenantId(tenantId), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Get a tenant's per-cluster engine quota ceiling */
export function getTenantsByTenantIdQuota(tenantId: number | string, opts?: { query?: { cluster?: string } }): Promise<{ cluster?: string; ceiling?: number }> {
  return apiClient.get<{ cluster?: string; ceiling?: number }>(paths.getTenantsByTenantIdQuota(tenantId) + toQuery(opts?.query ?? {}));
}

/** Set a tenant's per-cluster engine quota ceiling */
export function putTenantsByTenantIdQuota(tenantId: number | string, body: { cluster?: string; ceiling: number }): Promise<{ message?: string }> {
  return apiClient.post<{ message?: string }>(paths.putTenantsByTenantIdQuota(tenantId), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** List a tenant's engine-capacity reservations over a date range */
export function getTenantsByTenantIdReservations(tenantId: number | string, opts?: { query?: { from?: string; to?: string; cluster?: string } }): Promise<Reservation[]> {
  return apiClient.get<Reservation[]>(paths.getTenantsByTenantIdReservations(tenantId) + toQuery(opts?.query ?? {}));
}

/** List a tenant's role grants (member roster) */
export function getTenantsByTenantIdRoles(tenantId: number | string): Promise<RoleGrant[]> {
  return apiClient.get<RoleGrant[]>(paths.getTenantsByTenantIdRoles(tenantId));
}

/** Grant a role within a tenant */
export function postTenantsByTenantIdRoles(tenantId: number | string, body: { subject: string; email?: string; role: string }): Promise<void> {
  return apiClient.post<void>(paths.postTenantsByTenantIdRoles(tenantId), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Revoke a role within a tenant */
export function deleteTenantsByTenantIdRoles(tenantId: number | string, opts?: { query?: { subject?: string; role?: string } }): Promise<void> {
  return apiClient.request<void>(paths.deleteTenantsByTenantIdRoles(tenantId) + toQuery(opts?.query ?? {}), { method: 'DELETE' });
}

/** Grant a global role */
export function postRoles(body: { subject: string; email?: string; role: string }): Promise<void> {
  return apiClient.post<void>(paths.postRoles(), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Revoke a global role */
export function deleteRoles(opts?: { query?: { subject?: string; role?: string } }): Promise<void> {
  return apiClient.request<void>(paths.deleteRoles() + toQuery(opts?.query ?? {}), { method: 'DELETE' });
}

/** List registered clusters */
export function getClusters(): Promise<Cluster[]> {
  return apiClient.get<Cluster[]>(paths.getClusters());
}

/** Register a cluster (operator secret_ref, or BYOC kubeconfig) */
export function postClusters(body: { name: string; ingest_url: string; sidecar_image: string; namespace: string; secret_ref?: string; kubeconfig?: string }): Promise<Cluster> {
  return apiClient.post<Cluster>(paths.postClusters(), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Replace a cluster's ingest token */
export function postClustersByNameRotateIngestToken(name: number | string): Promise<{ ingest_token?: string }> {
  return apiClient.request<{ ingest_token?: string }>(paths.postClustersByNameRotateIngestToken(name), { method: 'POST' });
}

/** Get a registered cluster */
export function getClustersByName(name: number | string): Promise<Cluster> {
  return apiClient.get<Cluster>(paths.getClustersByName(name));
}

/** Update a cluster's deploy settings */
export function putClustersByName(name: number | string, body: { ingest_url?: string; sidecar_image?: string; namespace?: string }): Promise<Cluster> {
  return apiClient.post<Cluster>(paths.putClustersByName(name), new URLSearchParams(Object.entries(body).map(([k, v]) => [k, String(v)] as [string, string])));
}

/** Remove a cluster (rejected while it has an active run) */
export function deleteClustersByName(name: number | string): Promise<void> {
  return apiClient.request<void>(paths.deleteClustersByName(name), { method: 'DELETE' });
}

/** Push measurements from an engine pod */
export function postIngest(body: MetricBatch): Promise<void> {
  return apiClient.request<void>(paths.postIngest(), {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
}

/** Download an uploaded artifact */
export function getFilesByKindByIdByName(kind: number | string, id: number | string, name: number | string): Promise<void> {
  return apiClient.get<void>(paths.getFilesByKindByIdByName(kind, id, name));
}

// Query params serialize the way the backend's net/http router reads them:
// repeated keys for arrays, String() for scalars, undefined dropped.
function toQuery(query: Record<string, unknown>): string {
  const sp = new URLSearchParams();
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined) continue;
    if (Array.isArray(value)) {
      for (const item of value) sp.append(key, String(item));
    } else {
      sp.append(key, String(value));
    }
  }
  const s = sp.toString();
  return s ? `?${s}` : '';
}
